name: Generate plot

on:
  push:
  pull_request:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install numpy scipy matplotlib
    - name: Replace plt.show() with saving and run script
      run: |
        if grep -q "plt.show()" main.py; then
          sed -i "s/plt.show()/plt.savefig('trajectory.png',bbox_inches='tight')/" main.py
        fi
        python main.py
    - name: Add image to GitHub Actions summary
      run: |
        echo "![График](trajectory.png)" >> $GITHUB_STEP_SUMMARY
    - name: Upload plot as artifact
      uses: actions/upload-artifact@v4
      with:
        name: trajectory-plot
        path: trajectory.png
