name: Generate and publish plot
permissions:
  contents: write

on:
  push:
  pull_request:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      PYTHON_VERSION: '3.11'
      SCRIPT: 'main.py'
      IMAGE: 'trajectory.png'
      BRANCH_PREFIX: 'generated-plot-'
    steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: 0
        persist-credentials: true
    - name: setup-python
      uses: actions/setup-python@v4
      with:
        python-version: ${{ env.PYTHON_VERSION }}
    - name: install-deps
      run: |
        python -m pip install --upgrade pip
        pip install numpy scipy matplotlib
    - name: run script with Agg backend
      run: |
        python - <<'PY'
        import matplotlib
        matplotlib.use('Agg')
        import runpy, sys, traceback, os
        try:
            runpy.run_path('${{ env.SCRIPT }}', run_name='__main__')
        except Exception:
            traceback.print_exc()
            sys.exit(1)
        finally:
            os.system('ls -la')
        PY
    - name: verify output
      run: |
        ls -la
        if [ -f "${{ env.IMAGE }}" ]; then
          echo "${{ env.IMAGE }} found"
        else
          echo "${{ env.IMAGE }} NOT found"
          exit 1
        fi
    - name: create branch and push image
      env:
        BRANCH_NAME: ${{ env.BRANCH_PREFIX }}${{ github.run_id }}
      run: |
        git config user.name "github-actions[bot]"
        git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
        git switch -c "$BRANCH_NAME"
        mkdir -p .
        git add "${{ env.IMAGE }}"
        if git diff --staged --quiet; then
          echo "No changes to commit"
        else
          git commit -m "Add generated ${{ env.IMAGE }} from workflow #${{ github.run_id }}"
          git push origin "$BRANCH_NAME"
        fi
    - name: add image to Actions summary (raw.githubusercontent)
      env:
        BRANCH_NAME: ${{ env.BRANCH_PREFIX }}${{ github.run_id }}
        RAW_URL: "https://raw.githubusercontent.com/${{ github.repository }}/$BRANCH_NAME/${{ env.IMAGE }}"
      run: |
        echo "![График]($RAW_URL)" >> $GITHUB_STEP_SUMMARY
        echo "Raw URL: $RAW_URL"
    - name: upload artifact
      uses: actions/upload-artifact@v4
      with:
        name: trajectory-plot
        path: trajectory.png
