name: Generate and commit plot

permissions:
  contents: write

on:
  push:
  pull_request:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: 0
        persist-credentials: true
    - name: setup-python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'
    - name: install-deps
      run: |
        python -m pip install --upgrade pip
        pip install numpy scipy matplotlib
    - name: run script with Agg backend
      run: |
        python - <<'PY'
        import matplotlib
        matplotlib.use('Agg')
        import runpy, sys, traceback, os
        try:
            runpy.run_path('main.py', run_name='__main__')
        except Exception:
            traceback.print_exc()
            sys.exit(1)
        finally:
            os.system('ls -la')
        PY
    - name: verify output
      run: |
        ls -la
        if [ -f trajectory.png ]; then
          echo "trajectory.png found"
        else
          echo "trajectory.png NOT found"
          exit 1
        fi
    - name: add to summary
      run: |
        echo "![График](trajectory.png)" >> $GITHUB_STEP_SUMMARY
    - name: upload artifact
      uses: actions/upload-artifact@v4
      with:
        name: trajectory-plot
        path: trajectory.png
    - name: commit and push plot to new branch
      env:
        BRANCH_NAME: generated-plot-${{ github.run_id }}
      run: |
        git config user.name "github-actions[bot]"
        git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
        git switch -c "$BRANCH_NAME"
        git add trajectory.png
        if git diff --staged --quiet; then
          echo "No changes to commit"
        else
          git commit -m "Add generated trajectory.png from workflow #${{ github.run_id }}"
          git push origin "$BRANCH_NAME"
        fi
